# Generated by Django 4.2.3 on 2023-08-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.TextField(max_length=255)),
                ('chargerCour', models.CharField(max_length=255)),
                ('observation', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
